[package]
name = "ch3-functions"
version = "0.1.0"
authors = ["Clark <c.washington.h@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
